### ISSUE TITLE
[Review/Raehan] 코드 공유 감사합니다.

### ISSUE THREAD

**Issue by rae-han** [VENDREDl/React-Next#1]
안녕하세요. 코드 공유해주셔서 감사합니다!!

질문 있어 이슈 남깁니다.

atoms의 컴포넌트들이 대부분 React.ReactElement 타입을 가지고 있더라고요. 저는 ReactNode 타입만 써왔는데 알고 보니 ReactElement 타입이 더 좁은 타입이고 안전할거 같단 생각이 들었습니다. 혹시 어떤 의도를 가지고 사용하신건지 궁금합니다!

감사합니다.

**Comment by VENDREDl** [comment]
@rae-han 

[React 컴포넌트(children) 타이핑](https://handhand.tistory.com/279)

사실 무언가 큰 의도가 있었던 건 아닙니다(?) 도움이 될지는 모르겠지만..

저번 주 주간회의에서 아토믹 디자인 관련해서 얘기하셔서 이번 기회에 공부해 보고 최대한 구현하는 걸 목표로 했었는데요.
그 과정에서 children을 prop으로 받아서 사용해야 하는 부분이 많아졌습니다.

이번 프로젝트 이전에는 React.FC를 사용했었다가 안 쓰는 걸 추천한다고 하셔서 이번에는 광범위하게 사용 가능한 ReactNode를
사용했었는데요. 다른 타입들도 찾아보다 ReactElement는 JSX 요소만 받을 수 있다길래 사용해 봤는데 래한님 말씀처럼 ReactNode 안에 포함되어 있어 더 좋아 보여 선택한 부분이 있는 것 같습니다.

ReactNode와 ReactElement 중 어떤 것이 더 좋은지는 모르겠지만 제 구조에서는 ReactElement로 하는 것이 더 좋아 보였던 것 같습니다.

**Comment by rae-han** [comment]
@VENDREDl 감사합니다. 정보 공유까지 해주셔서 감사합니다. 저도 한번 더 생각해보고 어떻게 쓸지 고민을 해야할거 같단 생각이 들었습니다. 감사합니다!
